site_name: Yartsu
theme:
  name: material
site_url: https://gh.dayl.in/yartsu
repo_url: https://github.com/daylinmorgan/yartsu
edit_uri: edit/main/docs/
repo_name: daylinmorgan/yartsu

theme:
  name: material
  features:
    - navigation.indexes
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
