#!/usr/bin/env bash

set -euxo pipefail
THEME_MD="./docs/themes.md"

themes=$(yartsu --list-themes | tail -n +5 | cut -d' ' -f 3)

mkdir -p ./docs/themes
rm -f ./docs/themes/*
rm -f $THEME_MD
yartsu -o docs/themes/list.svg -- yartsu --list-themes

cat >>"$THEME_MD" <<EOF
# Themes

<p align='center'>
<img src="/yartsu/themes/list.svg" width="50%">
</p>

See below for example outputs of each.
EOF

for theme in $themes; do
	url="docs/themes/${theme}.svg"
	cat >>"$THEME_MD" <<EOF
=== "$theme"
    ![$theme](./themes/${theme}.svg)
EOF
	yartsu --theme "$theme" -o "$url" --demo -t "yartsu --theme ${theme} --demo"
done

echo "finished."
