name: GitHub Pages

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM

      - name: Install dependencies
        run: pdm install       # Then you can use pdm in the following steps.

      - name: Build Docs
        run: pdm run make docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
