name: 🚀 Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

env:
  app-name: yartsu

jobs:
  build-artifacts:
    uses: ./.github/workflows/build.yml

  pypi-release:
    uses: ./.github/workflows/pypi.yml

  create-release:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    needs:
      - build-artifacts
    steps:
      - uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist/

      - run: ls -R dist/

      - name: Generate New Nightly Release
        run: |
          gh release create ${{ github.ref }} ./dist/*/${{ env.app-name }}*

